# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: analysis/metadata_analysis.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='analysis/metadata_analysis.proto',
  package='surepy',
  syntax='proto2',
  serialized_pb=_b('\n analysis/metadata_analysis.proto\x12\x06surepy\"F\n\x10\x41nalysis_routine\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x11\n\talgorithm\x18\x02 \x01(\t\x12\x11\n\tparameter\x18\x03 \x01(\t\"\xe1\x01\n\tAMetadata\x12\x12\n\nidentifier\x18\x01 \x01(\t\x12\x0f\n\x07\x63omment\x18\x02 \x01(\t\x12\x15\n\rcreation_date\x18\x03 \x01(\x03\x12\x19\n\x11modification_date\x18\x04 \x01(\x03\x12(\n\x06method\x18\x05 \x01(\x0b\x32\x18.surepy.Analysis_routine\x12\'\n\x03map\x18\x07 \x03(\x0b\x32\x1a.surepy.AMetadata.MapEntry\x1a*\n\x08MapEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01')
)




_ANALYSIS_ROUTINE = _descriptor.Descriptor(
  name='Analysis_routine',
  full_name='surepy.Analysis_routine',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='surepy.Analysis_routine.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='algorithm', full_name='surepy.Analysis_routine.algorithm', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='parameter', full_name='surepy.Analysis_routine.parameter', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=44,
  serialized_end=114,
)


_AMETADATA_MAPENTRY = _descriptor.Descriptor(
  name='MapEntry',
  full_name='surepy.AMetadata.MapEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='surepy.AMetadata.MapEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='surepy.AMetadata.MapEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=_descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001')),
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=300,
  serialized_end=342,
)

_AMETADATA = _descriptor.Descriptor(
  name='AMetadata',
  full_name='surepy.AMetadata',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='identifier', full_name='surepy.AMetadata.identifier', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='comment', full_name='surepy.AMetadata.comment', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='creation_date', full_name='surepy.AMetadata.creation_date', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='modification_date', full_name='surepy.AMetadata.modification_date', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='method', full_name='surepy.AMetadata.method', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='map', full_name='surepy.AMetadata.map', index=5,
      number=7, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_AMETADATA_MAPENTRY, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=117,
  serialized_end=342,
)

_AMETADATA_MAPENTRY.containing_type = _AMETADATA
_AMETADATA.fields_by_name['method'].message_type = _ANALYSIS_ROUTINE
_AMETADATA.fields_by_name['map'].message_type = _AMETADATA_MAPENTRY
DESCRIPTOR.message_types_by_name['Analysis_routine'] = _ANALYSIS_ROUTINE
DESCRIPTOR.message_types_by_name['AMetadata'] = _AMETADATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Analysis_routine = _reflection.GeneratedProtocolMessageType('Analysis_routine', (_message.Message,), dict(
  DESCRIPTOR = _ANALYSIS_ROUTINE,
  __module__ = 'analysis.metadata_analysis_pb2'
  # @@protoc_insertion_point(class_scope:surepy.Analysis_routine)
  ))
_sym_db.RegisterMessage(Analysis_routine)

AMetadata = _reflection.GeneratedProtocolMessageType('AMetadata', (_message.Message,), dict(

  MapEntry = _reflection.GeneratedProtocolMessageType('MapEntry', (_message.Message,), dict(
    DESCRIPTOR = _AMETADATA_MAPENTRY,
    __module__ = 'analysis.metadata_analysis_pb2'
    # @@protoc_insertion_point(class_scope:surepy.AMetadata.MapEntry)
    ))
  ,
  DESCRIPTOR = _AMETADATA,
  __module__ = 'analysis.metadata_analysis_pb2'
  # @@protoc_insertion_point(class_scope:surepy.AMetadata)
  ))
_sym_db.RegisterMessage(AMetadata)
_sym_db.RegisterMessage(AMetadata.MapEntry)


_AMETADATA_MAPENTRY.has_options = True
_AMETADATA_MAPENTRY._options = _descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001'))
# @@protoc_insertion_point(module_scope)
