repos:
- repo: https://github.com/psf/black
  rev: 23.7.0
  hooks:
    - id: black
- repo: https://github.com/charliermarsh/ruff-pre-commit
  rev: v0.1.1
  hooks:
    - id: ruff
      args: [
        --output-format, grouped,
      ]
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.5.1
  hooks:
   -  id: mypy
      additional_dependencies: [
        'numpy',
        'types-protobuf',
        'types-requests',
        'types-tqdm',
        'pandas-stubs',
      ]
