repos:
- repo: https://github.com/psf/black
  rev: 23.1.0
  hooks:
    - id: black
- repo: https://github.com/charliermarsh/ruff-pre-commit
  rev: 'v0.0.247'
  hooks:
    - id: ruff
      args: [
        --format, grouped,
      ]
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.4.0
    hooks:
     -  id: mypy
        additional_dependencies: []
