repos:
- repo: https://github.com/psf/black-pre-commit-mirror
  rev: 24.8.0
  hooks:
    - id: black
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.6.9
  hooks:
    - id: ruff
      args: [
        --output-format, grouped,
      ]
