# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-20.04
  tools:
    python: "3.10"
  apt_packages:
    - git

# Build documentation in the docs/ directory with Sphinx
sphinx:
  builder: html
  configuration: docs/conf.py
  fail_on_warning: false

# If using Sphinx, optionally build your docs in additional formats such as PDF
formats:
  - pdf
#  - epub

# Optionally declare the Python requirements required to build your docs
python:
   install:
     - requirements: docs/requirements_rtd.txt
     - method: pip
       path: .
