#
# Further tools for surepy development
#
#
# Update existing environment: conda env update --file "./environment_dev.yml"
#
name: surepy

channels:
- conda-forge
- defaults

dependencies:
# Development related
- sphinx
- sphinx_rtd_theme
- nbval
- ipython
