#
# Tools for locan development
#
# Create new environment:
#    conda env create --file "./environment.yml" --file "./environment_dev.yml"
# Update existing environment:
#    conda env update --file "./environment.yml" --file "./environment_dev.yml"
#
name: locan

channels:
- conda-forge

dependencies:
############################################
# additions for development
############################################
# Python tests
- asv
- coverage

# Development
- black~=24.0
- build
- mypy
- numpy
- pandas-stubs
- pre-commit
- ruff
- twine
- types-networkx
- types-protobuf
- types-shapely
- types-tqdm

# Documentation
- ipython
- furo
- myst-nb
- sphinx
- sphinx-copybutton
- sphinx-autodoc-typehints

- pip:
    - ray[default]
