#
# Tools for locan development
#
# Update existing environment: conda env update --file "./environment_dev.yml"
#
name: locan

channels:
- conda-forge
- defaults

dependencies:
# Python
- cython
- pip
- tqdm
- qtpy!=2.3.0
- typing_extensions
- lazy_loader>=0.3

# Python tests
- pytest

# Scientific python
- numpy>1.20.0
- pandas
- scipy
- scikit-learn
- scikit-image
- matplotlib
- networkx
- shapely!=2.0.0,!=2.0.1
- lmfit

# Google
- protobuf

# File formats
- ruamel.yaml
- tifffile
- asdf
- # only needed for python < 3.11:
# - tomli>=1.1.0

# Data analysis tools
- boost-histogram
- fast-histogram

# Extra requirements
# - pyside2>=5.12.3
- pyside6
- colorcet
- trackpy
- napari
- mpl-scatter-density
- httpx
- h5py

# Various issues
- pydantic!=1.8.0

############################################
# additions for development
############################################

# Python tests
- asv
- coverage
- pytest

# Development
- black~=24.0
- build
- mypy
- numpy
- pandas-stubs
- pre-commit
- ruff
- twine
- types-protobuf
- types-tqdm

# Documentation
- ipython
- furo
- myst-nb
- sphinx
- sphinx-copybutton
- sphinx-autodoc-typehints

############################################
# additions from PyPI
############################################

- pip:
    - open3d!=0.12.0; python_version<'3.12'
    - ray[default]
