# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: surepy/data/metadata.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='surepy/data/metadata.proto',
  package='surepy',
  serialized_pb='\n\x1asurepy/data/metadata.proto\x12\x06surepy\"\xec\x01\n\x08Metadata\x12\x12\n\nidentifier\x18\x01 \x01(\t\x12\x17\n\x0fproduction_date\x18\x02 \x01(\x03\x12\x19\n\x11modification_date\x18\x03 \x01(\x03\x12\x0e\n\x06source\x18\x04 \x01(\t\x12\x1c\n\x05state\x18\x05 \x01(\x0e\x32\r.surepy.State\x12\x0f\n\x07history\x18\x06 \x03(\t\x12\x15\n\relement_count\x18\x07 \x01(\x03\x12\x13\n\x0b\x66rame_count\x18\x08 \x01(\x03\x12\x1c\n\x14\x61ncestor_identifiers\x18\t \x03(\t\x12\x0f\n\x07\x63omment\x18\n \x01(\t*+\n\x05State\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x07\n\x03RAW\x10\x01\x12\x0c\n\x08MODIFIED\x10\x02')

_STATE = _descriptor.EnumDescriptor(
  name='State',
  full_name='surepy.State',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RAW', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MODIFIED', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=277,
  serialized_end=320,
)

State = enum_type_wrapper.EnumTypeWrapper(_STATE)
UNKNOWN = 0
RAW = 1
MODIFIED = 2



_METADATA = _descriptor.Descriptor(
  name='Metadata',
  full_name='surepy.Metadata',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='identifier', full_name='surepy.Metadata.identifier', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='production_date', full_name='surepy.Metadata.production_date', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='modification_date', full_name='surepy.Metadata.modification_date', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='source', full_name='surepy.Metadata.source', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='state', full_name='surepy.Metadata.state', index=4,
      number=5, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='history', full_name='surepy.Metadata.history', index=5,
      number=6, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='element_count', full_name='surepy.Metadata.element_count', index=6,
      number=7, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='frame_count', full_name='surepy.Metadata.frame_count', index=7,
      number=8, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ancestor_identifiers', full_name='surepy.Metadata.ancestor_identifiers', index=8,
      number=9, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='comment', full_name='surepy.Metadata.comment', index=9,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=39,
  serialized_end=275,
)

_METADATA.fields_by_name['state'].enum_type = _STATE
DESCRIPTOR.message_types_by_name['Metadata'] = _METADATA

class Metadata(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _METADATA

  # @@protoc_insertion_point(class_scope:surepy.Metadata)


# @@protoc_insertion_point(module_scope)
