name:  CI checks with black, ruff, mypy, py3.12

on:
  workflow_dispatch:

env:
  PYTHON_VERSION: "3.12"

jobs:
  check:
    name: "CI with ubuntu, py3.12, pip"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: "Install and upgrade"
        run: |
          python -m pip install --upgrade pip
          python -m pip install black~=24.0 ruff
          python -m pip install mypy numpy types-requests types-protobuf pandas-stubs
      - name: "Format with black"
        run: black --check --diff "."
      - name: "Lint with ruff"
        run: ruff check --output-format=github "."
      - name: "Type check with mypy"
        run: mypy
