name: Test using Conda

on: [workflow_dispatch]

env:
  ENVIRONMENT_NAME: locan_env

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Create environment and install dependencies
      run: |
        conda install mamba -c conda-forge
        mamba create -n env.ENVIRONMENT_NAME -c conda-forge
        mamba env update --file environment.yml --name env.ENVIRONMENT_NAME
        conda activate env.ENVIRONMENT_NAME
    - name: Install locan
      run: |
        pip install .
    - name: Test with pytest
      run: |
        conda install pytest
        pytest
