name: Tests with python matrix, Mambaforge
# skips qt-related tests

on:
  schedule:
    - cron: "47 4 * * 4"
  workflow_dispatch:

defaults:
  run:
    shell: bash -l {0}


jobs:
  matrix-test-on-mambaforge:
    name: "Tests with linux,, py${{ matrix.python-version }}, Mambaforge"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11"]
    env:
      REQUIREMENTS_FILE: "environment-linux-py${{ matrix.python-version }}.yml"
    steps:
      - uses: actions/checkout@v3
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          activate-environment: locan
          environment-file: environment.yml
          miniforge-variant: Mambaforge
          miniforge-version: latest
          python-version: ${{ matrix.python-version }}
          use-mamba: true
      - name: "Install locan"
        run: |
          pip install .
      - name: "Run tests"
        run: pytest
      - name: "Freeze environment"
        run: conda env export > ${{ env.REQUIREMENTS_FILE }}
      - name: "Upload requirements file"
        uses: actions/upload-artifact@v3
        with:
          name: "${{ env.REQUIREMENTS_FILE }}"
          path: ${{ env.REQUIREMENTS_FILE }}
