name: Tests with matrix, pip

on:
  workflow_dispatch:

jobs:
  test-on-python:
    name: "Run (${{ matrix.os }}, ${{ matrix.python-version }}, pip)"
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu", "macos", "windows"]
        python-version: ["3.7", "3.8"]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: "Run locan with extra requirements"
        run: |
          pip install .[all]
          pytest
