name: Tests with ubuntu, current python, Mambaforge

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

defaults:
  run:
    shell: bash -l {0}

env:
  PYTHON_VERSION: 3.9

jobs:
  test-on-mambaforge:
    name: "Tests with ubuntu, py${{ env.PYTHON_VERSION }}, Mambaforge"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          activate-environment: locan
          environment-file: environment.yml
          miniforge-variant: Mambaforge
          miniforge-version: latest
          python-version: ${{ env.PYTHON_VERSION }}
          use-mamba: true
      - name: "Install locan"
        run: |
          pip install .
      - name: "Run tests"
        run: pytest
      - name: "Freeze environment"
        env:
          REQUIREMENTS_FILE: "environment-${{ runner.os }}-py${{ env.PYTHON_VERSION }}.yml"
        run: conda env export > ${{ env.REQUIREMENTS_FILE }}
      - name: "Upload requirements file"
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.REQUIREMENTS_FILE }}
          path: ./requirements/${{ env.REQUIREMENTS_FILE }}
