name: Tests with python matrix, pip, extra dependencies, qt
# includes qt-related tests

on:
  schedule:
    - cron: "47 4 * * 4"
  workflow_dispatch:

jobs:
  test-on-python:
    name: "Tests with linux, py${{ matrix.python-version }}, pip"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]
    env:
      REQUIREMENTS_FILE: "requirements-all-linux-py${{ matrix.python-version }}.yml"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      # For testing with Qt on linux
      - uses: tlambert03/setup-qt-libs@v1

      - name: "Install and upgrade"
        run: |
          python -m pip install --upgrade pip
          pip install pip-tools
      - name: "Run locan with extra requirements"
        run: |
          pip install pyside6 .[all]
      - name: "Run tests"
        uses: coactions/setup-xvfb@v1
        with:
          run: pytest
