name: Tests with ubuntu, Miniforge, py3.12
# skips qt-related tests

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

defaults:
  run:
    shell: bash -l {0}

env:
  OS: "linux"
  PYTHON_VERSION: "3.12"
  REQUIREMENTS_FILE: "environment-linux-py3.12.yml"

jobs:
  test-on-miniforge:
    name: "Tests with linux, py3.12, Miniforge"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          activate-environment: locan
          environment-file: environment.yml
          miniforge-version: latest
          python-version: ${{ env.PYTHON_VERSION }}
      - name: "Install locan"
        run: |
          pip install .
      - name: "Run tests"
        run: pytest
      - name: "Freeze environment"
        run: conda env export > ${{ env.REQUIREMENTS_FILE }}
      - name: "Upload requirements file"
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.REQUIREMENTS_FILE }}
          path: ${{ env.REQUIREMENTS_FILE }}
