name:  Tests with ubuntu, current python, pip and coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  OS: "linux"
  PYTHON_VERSION: "3.10"
  REQUIREMENTS_FILE: "requirements-all-linux-py3.10.txt"

jobs:
  test-on-python:
    name: "Tests with ubuntu, py3.10, pip-environment"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: "Install and upgrade"
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade coverage[toml]
          pip install pip-tools
      - name: "Install locan with extra requirements"
        run: |
          pip install .[all]
      - name: "Run tests"
        run: coverage run -m pytest --junitxml=./test-results-${{ env.PYTHON_VERSION }}.xml
      - name: "Prepare coverage reports"
        run: coverage xml
      - name: "Check coverage"
        run: coverage report --fail-under=80
      - name: "Upload coverage to CodeCov"
        uses: codecov/codecov-action@v2
        with:
          fail_ci_if_error: true
          files: coverage.xml
          flags: unittests
          name: "CodeCov report"
          verbose: true
      - name: "Freeze requirements"
        run: pip-compile pyproject.toml --extra test --output-file ${{ env.REQUIREMENTS_FILE }}
      - name: "Upload requirements file"
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.REQUIREMENTS_FILE }}
          path: ${{ env.REQUIREMENTS_FILE }}
