name: Tests with python matrix, pip, extra dependencies, qt
# includes qt-related tests

on:
  schedule:
    - cron: "47 4 * * 4"
  workflow_dispatch:

jobs:
  test-on-python:
    name: "Tests with linux, py${{ matrix.python-version }}, pip"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12"]
    env:
      REQUIREMENTS_FILE: "requirements-all-linux-py${{ matrix.python-version }}.yml"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      # For testing with Qt on linux
      - uses: tlambert03/setup-qt-libs@v1

      - name: "Install and upgrade"
        run: |
          python -m pip install --upgrade pip
          pip install pip-tools
      - name: "Run locan with extra requirements"
        run: |
          pip install .[all]
      - name: "Run tests"
        uses: coactions/setup-xvfb@v1
        with:
          run: pytest
      - name: "Freeze requirements"
        run: pip-compile pyproject.toml --extra test --output-file ${{ env.REQUIREMENTS_FILE }}
      - name: "Upload requirements file"
        uses: actions/upload-artifact@v3
        with:
          name: "${{ env.REQUIREMENTS_FILE }}"
          path: ${{ env.REQUIREMENTS_FILE }}