name: Tests with matrix, pip, py3.13
# skips qt-related tests

on:
  workflow_dispatch:

jobs:
  test-on-python:
    name: "Tests with ${{ matrix.os }}, py${{ matrix.python-version }}, pip"
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu", "macos", "windows"]
        python-version: ["3.13-dev"]
        exclude:
          - os: ["macos", "windows"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: "Install ubuntu libraries"
        if: runner.os == 'Linux'
        run: |
          sudo apt update 
          sudo apt -y install libegl1

      - name: "Install and upgrade"
        run: |
          python -m pip install --upgrade pip
          pip install pip-tools
      - name: "Install locan"
        run: pip install pyside6 .[test]
      - name: "Run tests"
        run: pytest
