name: Tests with matrix, Mambaforge

on:
  schedule:
    - cron: "47 4 * * 4"
  workflow_dispatch:

jobs:
  matrix-test-on-mambaforge:
    name: "Run (${{ matrix.os }}, ${{ matrix.python-version }}, Mambaforge)"
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu", "macos", "windows"]
        python-version: ["3.7", "3.8"]
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          activate-environment: locan
          environment-file: environment.yml
          miniforge-variant: Mambaforge
          miniforge-version: latest
          python-version: ${{ matrix.python-version }}
          use-mamba: true
      - name: "Run locan"
        shell: bash -l {0}
        run: |
          pip install .
          pytest
