name: Tests with ubuntu, py38, pip

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test-on-python:
    name: "Run (ubuntu, py38, pip)"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: "Run locan with extra requirements"
        run: |
          pip install cython numba hdbscan
          pip install .[all]
          pytest
